$ErrorActionPreference='Stop'
# React static server (:8082) - serves dist\ with python http.server.
# On every start, react\.env (VITE_PORTAL_API_BASE / VITE_AGENT_URL / VITE_EXPORTER_URL) is injected into
# dist\runtime-config.js (src/runtimeConfig.ts: runtime > VITE_ build value > page-host defaults
# Spring API / agent / exporter addresses take effect on restart without a rebuild.
# NOTE: ASCII-only comments/strings - PowerShell 5.1 reads BOM-less UTF-8 as ANSI.
$Python='C:\Python314\python.exe'
$Dist=Join-Path $PSScriptRoot 'dist'; $Log=Join-Path $PSScriptRoot 'logs'; $Run=Join-Path $PSScriptRoot 'run'; $PidFile=Join-Path $Run 'react.pid'
if (-not (Test-Path (Join-Path $Dist 'index.html'))) { throw '[react] dist missing - run build-react.ps1' }
if (-not (Test-Path $Python)) { throw "[react] python not found: $Python" }
New-Item -ItemType Directory -Force $Log,$Run | Out-Null
if (Test-Path $PidFile) { $pidValue=Get-Content $PidFile -ErrorAction SilentlyContinue; if ($pidValue -and (Get-Process -Id $pidValue -ErrorAction SilentlyContinue)) { Write-Host "[react] already running PID $pidValue"; exit 0 } }
# --- runtime-config.js (react\.env -> dist\runtime-config.js) ---
$KeyMap=[ordered]@{ VITE_PORTAL_API_BASE='portalApiUrl'; VITE_AGENT_URL='agentUrl'; VITE_EXPORTER_URL='exporterUrl' }
$Overrides=[ordered]@{}
$EnvFile=Join-Path $PSScriptRoot '.env'
if (Test-Path $EnvFile) {
  foreach ($line in Get-Content $EnvFile -Encoding UTF8) {
    if ($line -match '^\s*(VITE_(?:PORTAL_API_BASE|AGENT_URL|EXPORTER_URL))\s*=\s*(.*)$') {
      $v=$Matches[2].Trim().Trim('"').Trim("'")
      if ($v -ne '') { $Overrides[$KeyMap[$Matches[1]]]=$v }
    }
  }
}
$pairs=@($Overrides.Keys | ForEach-Object { '"' + $_ + '": "' + $Overrides[$_] + '"' }) -join ', '
$body="/* generated by start-react from react\.env at startup - do not edit */`nwindow.__TVM_CONFIG__ = {$pairs};`n"
[System.IO.File]::WriteAllText((Join-Path $Dist 'runtime-config.js'), $body, (New-Object System.Text.UTF8Encoding($false)))
if ($pairs) { Write-Host "[react] runtime-config: $pairs (react\.env - change takes effect on restart)" } else { Write-Host '[react] runtime-config: no override - same-origin Spring API / page-host agent-exporter defaults' }
$p=Start-Process $Python -ArgumentList @('-m','http.server','8082','--bind','0.0.0.0','--directory',$Dist) -WorkingDirectory $PSScriptRoot -RedirectStandardOutput (Join-Path $Log 'react.out.log') -RedirectStandardError (Join-Path $Log 'react.err.log') -WindowStyle Hidden -PassThru
$p.Id | Set-Content $PidFile
Write-Host "[react] started PID $($p.Id) - http://localhost:8082"
