// ===== 20260916 추가 시작 : 실시간 server_status API =====
import { runtimeOverride } from "../runtimeConfig";
export interface RealtimeQueryDto {hostname:string;hostip:string;serverPort:number|null;instanceId:string;service:string;connectionId:number|null;statementId:number|null;statementStartTime:string|null;statementStatus:string;statementStatusTimeSeconds:number|null;classifiedState:string;longRunning:boolean|null;gpuId:number|null;giId:number|null;cpuUsagePercent:number|null;memoryUsedBytes:number|null;memoryTotalBytes:number|null;memoryUsagePercent:number|null;diskUsedBytes:number|null;diskTotalBytes:number|null;diskUsagePercent:number|null;gpuMemoryUsedMib:number|null;gpuMemoryTotalMib:number|null;gpuMemoryUsagePercent:number|null;grEngineActivePercent:number|null}
export interface StatementDetailDto {hostip:string;serverPort:number|null;instanceId:string;service:string;connectionId:number|null;statementId:number|null;statementStartTime:string|null;statementStatus:string;statementStatusTimeSeconds:number|null;classifiedState:string;statement:string;clientIp:string;userId:string}
const base=()=>((runtimeOverride("portalApiUrl")??import.meta.env.VITE_PORTAL_API_BASE??"") as string).trim().replace(/\/$/,"");
const fmt=(ms:number)=>{const d=new Date(ms),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`};
export async function fetchRealtime(startMs:number,endMs:number,hostname:string,gpu:string,worker:string,signal?:AbortSignal){const q=new URLSearchParams({startTime:fmt(startMs),endTime:fmt(endMs)});if(hostname)q.set("hostname",hostname);if(gpu)q.set("gpuId",gpu);const m=worker.match(/(\d)(\d)$/);if(m){if(!gpu)q.set("gpuId",m[1]);q.set("giId",m[2]);}const r=await fetch(`${base()}/api/aireactechartdashboard/main/realtime?${q}`,{signal,credentials:"include"});if(!r.ok)throw new Error(`Realtime API HTTP ${r.status}`);return r.json() as Promise<RealtimeQueryDto[]>}
export async function fetchRealtimeStatement(connectionId:number,statementId:number,signal?:AbortSignal){const q=new URLSearchParams({connectionId:String(connectionId),statementId:String(statementId)});const r=await fetch(`${base()}/api/aireactechartdashboard/main/realtime/statement?${q}`,{signal,credentials:"include"});if(!r.ok)throw new Error(`Statement detail HTTP ${r.status}`);return r.json() as Promise<StatementDetailDto>}
// ===== 20260916 추가 끝 : 실시간 server_status API =====
